/**
 * Reusable email dispatch service using the Resend API.
 * Dispatches lead notifications to the client inbox asynchronously.
 */
export async function sendLeadNotification({ firstName, lastName, email, phone, interest, message }) {
  const apiKey = 're_CMDgaTYB_8E4Jj2bd9YH44vZnVCZ5GXFP';
  const recipient = 'jrgroupglobal@gmail.com';

  const subject = `New Website Inquiry: ${interest || 'General Contact'}`;
  const htmlContent = `
    <h2>New Luxury Real Estate Lead</h2>
    <p><strong>Name:</strong> ${firstName} ${lastName}</p>
    <p><strong>Email:</strong> ${email}</p>
    <p><strong>Phone:</strong> ${phone || 'N/A'}</p>
    <p><strong>Area of Interest:</strong> ${interest || 'General Inquiry'}</p>
    <p><strong>Message:</strong></p>
    <blockquote style="background: #f9f9f9; border-left: 5px solid #ccc; padding: 10px 15px; margin: 10px 0;">
      ${(message || 'No message provided.').replace(/\n/g, '<br/>')}
    </blockquote>
    <hr/>
    <p style="font-size: 11px; color: #777;">Notification generated by THE J website portal.</p>
  `;

  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        from: 'onboarding@resend.dev',
        to: recipient,
        subject: subject,
        html: htmlContent
      })
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.warn('Resend API response not OK:', response.status, errorText);
    } else {
      const data = await response.json();
      console.log('Resend notification dispatched successfully:', data);
    }
  } catch (err) {
    // Catch network errors (like CORS warnings in local testing/sandbox) gracefully
    console.error('Network error dispatching email notification:', err);
  }
}

/**
 * Simple client-side rate limiting to prevent spam submissions.
 * Enforces a 30-second cooldown and a maximum of 5 submissions per hour per device.
 */
export function checkRateLimit() {
  const now = Date.now();
  const COOLDOWN = 30 * 1000; // 30 seconds cooldown
  const ONE_HOUR = 60 * 60 * 1000; // 1 hour window
  
  try {
    let submissions = JSON.parse(localStorage.getItem('jj_form_submissions') || '[]');
    
    // Check if the last submission was too recent (cooldown)
    if (submissions.length > 0) {
      const lastSubmission = submissions[submissions.length - 1];
      if (now - lastSubmission < COOLDOWN) {
        return { allowed: false, reason: 'cooldown' };
      }
    }
    
    // Filter out submissions older than 1 hour
    submissions = submissions.filter(timestamp => (now - timestamp) < ONE_HOUR);
    
    if (submissions.length >= 5) {
      return { allowed: false, reason: 'hourly' };
    }
    
    // Log this submission
    submissions.push(now);
    localStorage.setItem('jj_form_submissions', JSON.stringify(submissions));
    return { allowed: true };
  } catch (e) {
    console.error('Error checking rate limit:', e);
    return { allowed: true }; // Fallback to allowing if localStorage fails
  }
}
